{
 "title": "Demo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "95th percentile request latency ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, path, method) (rate(demo_api_request_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "{{path}} - {{method}}"
      }
     ]
    },
    {
     "title": "Top 3 rates",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(3, sum by(path, method) (rate(demo_api_request_duration_seconds_count[5m])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(demo_cpu_usage_seconds_total{mode=\"idle\"}[5m]))\r\n/\r\non(instance) group_left () demo_num_cpus",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}